---
- name: Install Apache web server
  hosts: webserver
  become: true

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Enable Apache
      service:
        name: httpd
        state: started
        enabled: true

